$kind: http-example
request:
  url: "{{protocol}}://{{server}}:{{port}}/v2/tasks/:taskID"
  method: PATCH
  headers:
    Content-Type: application/json
  pathVariables:
    - key: taskID
      value: "14729"
      description: taskID of the task you are updating
  body:
    type: text
    content: |-
      {
          "name": "Do this task please!",
          "locationID": 163,
          "assetID": 1,
          "due": 1564605614,
          "type": 6,
          "assignment": 341,
          "assignmentType": "user",
          "priority": 3,
          "description": "this is a test task",
          "requestName": "requtest name",
          "requestEmail": "requestemail@domain.com",
          "requestPhone": "1111111111",
          "requestDescription": "request description",
          "status": 1,
          "meta1": "meta1",
          "meta2": "meta2",
          "meta3": "meta3",
          "geoLocation":     {
            "type": "Feature",
            "properties": {"name": "Salt Lake City"},
            "geometry": {
              "type": "Point",
              "coordinates": [
                -111.9012451171875,
                40.76962180287486
              ]
            }
          }
      }
response:
  statusCode: 200
  statusText: OK
  headers:
    Content-Security-Policy: "default-src 'self';base-uri
      'self';block-all-mixed-content;font-src 'self' https:
      data:;frame-ancestors 'self';img-src 'self' data:;object-src
      'none';script-src 'self';script-src-attr 'none';style-src 'self' https:
      'unsafe-inline';upgrade-insecure-requests"
    X-DNS-Prefetch-Control: off
    Expect-CT: max-age=0
    X-Frame-Options: SAMEORIGIN
    Strict-Transport-Security: max-age=15552000; includeSubDomains
    X-Download-Options: noopen
    X-Content-Type-Options: nosniff
    X-Permitted-Cross-Domain-Policies: none
    Referrer-Policy: no-referrer
    X-XSS-Protection: "0"
    API-Feedback-Link: https://portal.productboard.com/zodsn5nylisgwqkcbx9rh6kp/
    Date: Thu, 24 Mar 2022 15:58:10 GMT
    Connection: keep-alive
    Keep-Alive: timeout=5
    Content-Length: "0"
  body:
    type: text
    content: ""
order: 1000
