$kind: http-request
description: |-
  This request adds a comment to a task.

  <table><tbody><tr><th>Parameter</th><th>Type</th><th>Required?</th><th>Description</th></tr><tr><td><div>comment</div><div contenteditable="false"><div><div><div></div></div></div><div></div></div></td><td><div>String</div><div contenteditable="false"><div><div><div></div></div></div><div></div></div></td><td><div>Required</div><div contenteditable="false"><div><div><div></div></div></div><div></div></div></td><td><div>The comment to be added.</div><div contenteditable="false"><div><div><div></div></div></div><div></div></div></td></tr><tr><td><div>showExternalUsers</div><div contenteditable="false"><div><div><div></div></div></div><div></div></div></td><td><div>Boolean</div><div contenteditable="false"><div><div><div></div></div></div><div></div></div></td><td><div>Optional</div><div contenteditable="false"><div><div><div></div></div></div><div></div></div></td><td><div>This will show the comment to external users. The default value is true.</div><div contenteditable="false"><div><div><div></div></div></div><div></div></div></td></tr></tbody></table>
url: "{{protocol}}://{{server}}:{{port}}/v2/tasks/:taskID/comments"
method: POST
pathVariables:
  - key: taskID
    value: "19696"
    description: taskID of the task you are adding a comment to.
body:
  type: json
  content: "{\r

    \t\"comment\": \"complete the task\",\r

    \    \"showExternalUsers\": false\r

    }"
scripts:
  - type: afterResponse
    code: "pm.test(\"response must be valid and have a body\", function () {\r

      \     // assert that the status code is 200\r

      \     pm.response.to.be.ok; // info, success, redirection,
      clientError,  serverError, are other variants\r

      \     // assert that the response has a valid JSON body\r

      \     pm.response.to.be.withBody;\r

      \     pm.response.to.be.json; // this assertion also checks if a
      body  exists, so the above check is not needed\r

      });"
    language: text/javascript
examples: ./.resources/Add Task Comments.resources/examples
order: 2000
