$kind: http-example
request:
  url: "{{protocol}}://{{server}}:{{port}}/v2/tasks/:taskID/invoices/:invoiceID/f\
    ile"
  method: PUT
  pathVariables:
    - key: taskID
      value: "15188"
      description: The taskID of the invoice you want add the file to.
    - key: invoiceID
      value: "311"
      description: The invoiceID of the invoice you want to attach the file to.
  body:
    type: formdata
    content:
      - type: file
        key: file
        src: /C:/Users/Hely Mehta/Desktop/basic.txt
response:
  statusCode: 200
  statusText: OK
  headers:
    Content-Security-Policy: "default-src 'self';base-uri
      'self';block-all-mixed-content;font-src 'self' https:
      data:;frame-ancestors 'self';img-src 'self' data:;object-src
      'none';script-src 'self';script-src-attr 'none';style-src 'self' https:
      'unsafe-inline';upgrade-insecure-requests"
    X-DNS-Prefetch-Control: off
    Expect-CT: max-age=0
    X-Frame-Options: SAMEORIGIN
    Strict-Transport-Security: max-age=15552000; includeSubDomains
    X-Download-Options: noopen
    X-Content-Type-Options: nosniff
    X-Permitted-Cross-Domain-Policies: none
    Referrer-Policy: no-referrer
    X-XSS-Protection: "0"
    API-Feedback-Link: https://portal.productboard.com/zodsn5nylisgwqkcbx9rh6kp/
    Date: Fri, 01 Apr 2022 01:24:54 GMT
    Connection: keep-alive
    Keep-Alive: timeout=5
    Content-Length: "0"
  body:
    type: text
    content: ""
order: 1000
