$kind: http-request
description: This Request deletes a Role.  This will also remove the Role from
  any User it is assigned to.
url: "{{protocol}}://{{server}}:{{port}}/v2/roles/:roleID"
method: DELETE
pathVariables:
  - key: roleID
    value: "{{roleID}}"
    description: The roleID of the role you are deleting
scripts:
  - type: afterResponse
    code: "pm.test(\"response is ok\", function () {\r

      \    pm.response.to.have.status(200);\r

      });"
    language: text/javascript
examples: ./.resources/Delete Role.resources/examples
order: 4000
