$kind: http-example
request:
  url: ""
  method: GET
response:
  statusCode: 200
  statusText: OK
  body:
    type: text
    content: |-
      [
          {
              "workRequestSubmissionId": 1,
              "status": "approved",
              "createdByUserId": 1234,
              "createdAt": "2025-06-20T20:51:13.000Z",
              "customerID": 1234,
              "updatedAt": "2025-08-18T16:56:27.000Z",
              "deletedAt": "2025-06-20T14:51:13.000Z",
              "reviewedByUserId": 1234,
              "reviewedAt": "2025-08-18T16:56:27.000Z",
              "reviewedReason": null,
              "additionalNotes": null,
              "locationID": 1234,
              "assetID": 0,
              "priorityID": null,
              "dueDateUnit": "days",
              "requestTitle": "test",
              "requestInformation": {
                  "customerCode": "fdle6w1234",
                  "requesterEmail": "test.test@limblecmms.com",
                  "requesterName": "",
                  "requesterPhone": "8018773501",
                  "timeUnix": 1750437000,
                  "customTag": "",
                  "dueDate": 0,
                  "geoLocation": "null",
                  "customFieldOne": "",
                  "customFieldTwo": "",
                  "customFieldThree": "",
                  "customFieldOneTitle": "global setting",
                  "customFieldTwoTitle": "Custom field 2 instructions 22222",
                  "customFieldThreeTitle": "Custom field 3 instructions  33333",
                  "customFieldDropdownAnswerOne": "",
                  "customFieldDropdownAnswerTwo": "",
                  "customFieldDropdownAnswerThree": "",
                  "customDropdownTitleOne": "",
                  "customDropdownTitleTwo": "a",
                  "customDropdownTitleThree": "",
                  "customDropdownOptionsOne": [
                      {
                          "userID": -1,
                          "profileID": -1,
                          "tags": "@Dryer Vent;@Bill to Parent;",
                          "priority": -1,
                          "name": "",
                          "hint": "",
                          "checklistID": 0,
                          "order": 1,
                          "showExtra": true,
                          "option": "",
                          "priorityObj": {
                              "change": false
                          }
                      }
                  ]
              }
      ]
order: 1000
