$kind: http-request
description: |-
  StartFragment

  .expect('Content-Type', /json/);

  EndFragment
url: "{{protocol}}://{{server}}:{{port}}/v2/tasks/:taskID/invoices/"
method: PUT
pathVariables:
  - key: taskID
    value: "15188"
    description: The taskID of the task you're attaching an invoice to.
body:
  type: json
  content: "{\r

    \    \"cost\": 10.10,\r

    \    \"description\": \"testing\"\r

    }"
examples: ./.resources/Attach an Invoice to task.resources/examples
order: 3000
