$kind: http-example
request:
  url: "{{protocol}}://{{server}}:{{port}}/v2/tasks/:taskID/comments"
  method: GET
  queryParams:
    - key: cursor
      value: "0"
      disabled: true
      description: This parameter is a cursor that selects what commentID you want to
        start receiving results at. e.g. passing 137 here will only get you
        parts with an id greater than 137.
    - key: limit
      value: "100"
      disabled: true
      description: This parameter is a result limiter. The default is set to return no
        more than 100 results at one time.
  pathVariables:
    - key: taskID
      value: "19696"
      description: taskID of the task you are getting comments for.
response:
  statusCode: 200
  statusText: OK
  headers:
    Content-Security-Policy: "default-src 'self';base-uri
      'self';block-all-mixed-content;font-src 'self' https:
      data:;frame-ancestors 'self';img-src 'self' data:;object-src
      'none';script-src 'self';script-src-attr 'none';style-src 'self' https:
      'unsafe-inline';upgrade-insecure-requests"
    X-DNS-Prefetch-Control: off
    Expect-CT: max-age=0
    X-Frame-Options: SAMEORIGIN
    Strict-Transport-Security: max-age=15552000; includeSubDomains
    X-Download-Options: noopen
    X-Content-Type-Options: nosniff
    X-Permitted-Cross-Domain-Policies: none
    Referrer-Policy: no-referrer
    X-XSS-Protection: "0"
    API-Feedback-Link: https://portal.productboard.com/zodsn5nylisgwqkcbx9rh6kp/
    X-RateLimit-Limit: "4000"
    X-RateLimit-Minute-Limit: "360"
    X-RateLimit-Remaining: "3691"
    X-RateLimit-First-Call: "1694457371"
    X-RateLimit-Minute-Remaining: "359"
    X-RateLimit-Minute-First-Call: "1694458796"
    Content-Type: application/json; charset=utf-8
    Content-Length: "952"
    ETag: W/"3b8-4xNVfUOSzHrJkywcvVLOPDmMH4E"
    Date: Mon, 11 Sep 2023 18:59:56 GMT
    Connection: keep-alive
    Keep-Alive: timeout=5
  body:
    type: json
    content: >-
      [
          {
              "commentID": 18018,
              "comment": "Triggered at: 41 Mileage | Schedule set at: Every 15 Mileage",
              "commentFiles": [],
              "timestamp": 1694110194,
              "userID": 340,
              "commentEmailAddress": null,
              "showExternalUsers": true
          },
          {
              "commentID": 18019,
              "comment": "This Task was assigned to Unassigned",
              "commentFiles": [],
              "timestamp": 1694110195,
              "userID": 340,
              "commentEmailAddress": null,
              "showExternalUsers": true
          },
          {
              "commentID": 18031,
              "comment": "This Task's Status was changed from name4 to name4",
              "commentFiles": [],
              "timestamp": 1694457643,
              "userID": 340,
              "commentEmailAddress": null,
              "showExternalUsers": true
          },
          {
              "commentID": 18032,
              "comment": "This Task's Status was changed from name4 to name444",
              "commentFiles": [],
              "timestamp": 1694457678,
              "userID": 340,
              "commentEmailAddress": null,
              "showExternalUsers": true
          },
          {
              "commentID": 18057,
              "comment": "task name",
              "commentFiles": [],
              "timestamp": 1694458584,
              "userID": 340,
              "commentEmailAddress": null,
              "showExternalUsers": true
          },
          {
              "commentID": 18058,
              "comment": "complete the task",
              "commentFiles": [],
              "timestamp": 1694458628,
              "userID": 340,
              "commentEmailAddress": null,
              "showExternalUsers": false
          }
      ]
order: 1000
