$kind: http-example
request:
  url: "{{protocol}}://{{server}}:{{port}}/v2/tasks/instructions/:instructionID/i\
    mage"
  method: PUT
  pathVariables:
    instructionID: "59271"
  body:
    type: formdata
    content:
      - type: file
        key: image
        src: pic.png
response:
  statusCode: 200
  statusText: OK
  headers:
    Content-Security-Policy: "default-src 'self';base-uri
      'self';block-all-mixed-content;font-src 'self' https:
      data:;frame-ancestors 'self';img-src 'self' data:;object-src
      'none';script-src 'self';script-src-attr 'none';style-src 'self' https:
      'unsafe-inline';upgrade-insecure-requests"
    X-DNS-Prefetch-Control: off
    Expect-CT: max-age=0
    X-Frame-Options: SAMEORIGIN
    Strict-Transport-Security: max-age=15552000; includeSubDomains
    X-Download-Options: noopen
    X-Content-Type-Options: nosniff
    X-Permitted-Cross-Domain-Policies: none
    Referrer-Policy: no-referrer
    X-XSS-Protection: "0"
    API-Feedback-Link: https://portal.productboard.com/zodsn5nylisgwqkcbx9rh6kp/
    Content-Type: application/json; charset=utf-8
    Content-Length: "38"
    ETag: W/"26-QcQnnIUl42jtDnowArRi/CUbQ3s"
    Date: Tue, 19 Apr 2022 22:52:27 GMT
    Connection: keep-alive
    Keep-Alive: timeout=5
  body:
    type: json
    content: |-
      {
          "filename": "165040874634324-pic.png"
      }
order: 1000
