$kind: http-example
request:
  url: "{{protocol}}://{{server}}:{{port}}/v2/tasks/parts"
  method: GET
  headers:
    Content-Type: application/json
  queryParams:
    - key: tasks
      value: 5,10,1112
      disabled: true
      description: This parameter is used to get parts attached to a list of tasks.
        This parameter accepts a comma delimited list of task IDs.
    - key: parts
      value: 121,112,553
      disabled: true
      description: This parameter is used to get only certain. This parameter accepts
        a comma delimited list of task IDs.
    - key: cursor
      value: "137"
      disabled: true
      description: This parameter is a cursor that selects what id you want to start
        receiving results at. e.g. passing 137 here will only get you assets
        with an id greater than 137.
    - key: limit
      value: "100"
      disabled: true
      description: This parameter is a result limiter. The default is set to return no
        more than 100 results at one time.
response:
  statusCode: 200
  statusText: OK
  headers:
    X-DNS-Prefetch-Control: off
    X-Frame-Options: SAMEORIGIN
    Strict-Transport-Security: max-age=15552000; includeSubDomains
    X-Download-Options: noopen
    X-Content-Type-Options: nosniff
    X-XSS-Protection: 1; mode=block
    API-Feedback-Link: https://portal.productboard.com/zodsn5nylisgwqkcbx9rh6kp/
    Content-Type: application/json; charset=utf-8
    Content-Length: "7599"
    ETag: W/"1daf-663+1WJFu+qZ3/PSNvpzN5CTDiI"
    Date: Tue, 14 Jan 2020 00:24:35 GMT
    Connection: keep-alive
  body:
    type: json
    content: |-
      [
          {
              "relationID": 2,
              "partID": 2,
              "taskID": 8,
              "quantity": 1,
              "lastEdited": 1519084797,
              "usedPrice": 0,
              "partName": "X1161P Projector Lamp",
              "poItemID": 0
          },
          {
              "relationID": 3,
              "partID": 3,
              "taskID": 10,
              "quantity": 5,
              "lastEdited": 1519084797,
              "usedPrice": 0,
              "partName": "Stain Cleaner",
              "poItemID": 0
          },
          {
              "relationID": 8,
              "partID": 4,
              "taskID": 31,
              "quantity": 1,
              "lastEdited": 1519084797,
              "usedPrice": 0,
              "partName": "Spark Plugs",
              "poItemID": 0
          }
      ]
order: 1000
