$kind: http-request
description: >-
  This request creates a new Role.  Roles are used for access management in
  Limble. Once a Role is created you can assign permissions to that Role via the
  web application and then assign Users to that Role to control what that User
  can do in Limble.


  <table class="apiTable">
  	<thead>
  		<tr>
  			<th>Parameter</th>
  			<th>Type</th>
  			<th>Required?</th>
  			<th>Description</th>
  		</tr>
  	</thead>
  	<tbody>
  		<tr>
  			<td>name</td>
  			<td>String</td>
  			<td>Required</td>
  			<td>The name of the role.</td>
  		</tr>
  	</tbody>
  </table>
url: "{{protocol}}://{{server}}:{{port}}/v2/roles/"
method: POST
headers:
  Content-Type: application/json
body:
  type: text
  content: |-
    {
    	"name": "test role"
    }
scripts:
  - type: beforeRequest
    code: |-
      const roleName = `role_name_${Math.floor(Math.random() * 10000000)}`;

      pm.globals.set('roleName', roleName);
    language: text/javascript
  - type: afterResponse
    code: |-
      const roleID = pm.response.json().roleID;

      pm.test("response is created", () => {
          pm.response.to.have.status(201);
      });

      pm.test("location header is valid", () => {
          const locationHeader = postman.getResponseHeader('Location')
          pm.expect(locationHeader).to.eql(`/v2/roles/?roles=${roleID}`);
      });

      pm.globals.set('roleID', roleID);
    language: text/javascript
examples: ./.resources/Create Role.resources/examples
order: 2000
