$kind: http-example
request:
  url: "{{protocol}}://{{server}}:{{port}}/v2/tasks/:taskID/comments"
  method: POST
  pathVariables:
    - key: taskID
      value: "19696"
      description: taskID of the task you are adding a comment to.
  body:
    type: json
    content: "{\r

      \t\"comment\": \"complete the task\",\r

      \    \"showExternalUsers\": false\r

      }"
response:
  statusCode: 200
  statusText: OK
  body:
    type: text
    content: ""
order: 1000
