$kind: http-example
request:
  url: "{{protocol}}://{{server}}:{{port}}/v2/tasks/"
  method: POST
  headers:
    Content-Type: application/json
  body:
    type: text
    content: |-
      {
          "name": "task name",
          "locationID": 163,
          "due": 1564605614,
          "type": 6,
          "priority": 3,
          "assignment": 341,
          "assignmentType": "user",
          "description": "this is a test task",
          "requestName": "request name",
          "requestEmail": "requestemail@domain.com",
          "requestPhone": "1234567890",
          "requestDescription": "request description",
          "meta1": "Meta1",
          "meta2": "Meta2",
          "meta3": "Meta3",
          "geoLocation": {
              "type":"Feature",
              "properties":{
                  "name":"Lehi"
                  },
              "geometry":{
                  "type":"Point",
                  "coordinates":[-111.84906005859375,40.39075031913329]
              }
          }
      }
response:
  statusCode: 201
  statusText: Created
  headers:
    Content-Security-Policy: "default-src 'self';base-uri
      'self';block-all-mixed-content;font-src 'self' https:
      data:;frame-ancestors 'self';img-src 'self' data:;object-src
      'none';script-src 'self';script-src-attr 'none';style-src 'self' https:
      'unsafe-inline';upgrade-insecure-requests"
    X-DNS-Prefetch-Control: off
    Expect-CT: max-age=0
    X-Frame-Options: SAMEORIGIN
    Strict-Transport-Security: max-age=15552000; includeSubDomains
    X-Download-Options: noopen
    X-Content-Type-Options: nosniff
    X-Permitted-Cross-Domain-Policies: none
    Referrer-Policy: no-referrer
    X-XSS-Protection: "0"
    API-Feedback-Link: https://portal.productboard.com/zodsn5nylisgwqkcbx9rh6kp/
    Location: /v2/tasks/?tasks=14729
    Content-Type: application/json; charset=utf-8
    Content-Length: "16"
    ETag: W/"10-TFA9Ccb5kHYq7zKjE0aOqL76fzY"
    Date: Thu, 24 Mar 2022 15:42:25 GMT
    Connection: keep-alive
    Keep-Alive: timeout=5
  body:
    type: json
    content: |-
      {
          "taskID": 14729
      }
order: 2000
