$kind: http-request
description: >-
  This request will create a new Instruction for a Task.


  <table class="apiTable">
  	<thead>
  		<tr>
  			<th>Parameter</th>
  			<th>Type</th>
  			<th>Required?</th>
  			<th>Description</th>
  		</tr>
  	</thead>
  	<tbody>
  		<tr>
  			<td>type</td>
  			<td>Int</td>
  			<td>Required</td>
  			<td>The type of each checklist item.<br />
  				1 = Check Box;
   2 = Option List;
  				3 = Text Box;
  4 = Dropdown List;
  				5 = Date Picker;
  				7 = Label;
  				9 = File or Picture Attachment;
  				11 = Deadline Date Picker;
  				13 = Number;
  				14 = Start WO;
  				15 = Capture Signature.<br />
  				Item types not listed here are not currently supported.  If you would like another item type to be supported, please contact us at product@limblecmms.com.
  			</td>
  		</tr>
  		<tr>
  			<td>instruction</td>
  			<td>string</td>
  			<td>Required</td>
  			<td>The text that guides a User on what to do on this Instruction.</td>
  		</tr>
  		<tr>
  			<td>parentInstructionID</td>
  			<td>Int</td>
  			<td>Required</td>
  			<td>If this is set this Instruction is a 'child' or sub-instruction. This value is the id of the Instruction's parent.  A value of 0 means it does not have a parent.</td>
  		</tr>
          <tr>
  			<td>parentInstructionOptionID</td>
  			<td>Int</td>
  			<td>Optional</td>
  			<td>If type is set to 2,4 and a parentInstructionID of an existing option/dropdown list is set then the parentInstructionOptionID needs to be set as the ID of the option for which a child option/dropdown list needs to be added.</td>
  		</tr>
  	</tbody>
  </table>
url: "{{protocol}}://{{server}}:{{port}}/v2/tasks/:taskID/instructions/"
method: POST
headers:
  Content-Type: application/json
pathVariables:
  - key: taskID
    value: "{{taskID}}"
    description: taskID of the task you are adding instructions to.
body:
  type: text
  content: |-
    {
        "type": 1,
        "instruction": "Remove oil filter."
    }
scripts:
  - type: afterResponse
    code: |
      const instructionID = pm.response.json().instructionID;

      pm.test("response is created", () => {
          pm.response.to.have.status(201);
      });

      taskID = pm.globals.get('taskID');
      pm.test("location header is valid", () => {
          const locationHeader = postman.getResponseHeader('Location')
          pm.expect(locationHeader).to.eql(`/v2/tasks/${taskID}/instructions`);
      })

      pm.globals.set('instructionID', instructionID);
    language: text/javascript
examples: ./.resources/New Task Instruction.resources/examples
order: 3000
