$kind: http-example
request:
  url: "{{protocol}}://{{server}}:{{port}}/v2/tasks//instructions/:instructionID/\
    options/:instructionOptionID"
  method: DELETE
  pathVariables:
    - key: instructionID
      value: "49343"
      description: instructionID of the instruction whose option you are deleting.
    - key: instructionOptionID
      value: "7097"
      description: instructionOptionID of the instruction option you are deleting.
response:
  statusCode: 200
  statusText: OK
  headers:
    Content-Security-Policy: "default-src 'self';base-uri
      'self';block-all-mixed-content;font-src 'self' https:
      data:;frame-ancestors 'self';img-src 'self' data:;object-src
      'none';script-src 'self';script-src-attr 'none';style-src 'self' https:
      'unsafe-inline';upgrade-insecure-requests"
    X-DNS-Prefetch-Control: off
    Expect-CT: max-age=0
    X-Frame-Options: SAMEORIGIN
    Strict-Transport-Security: max-age=15552000; includeSubDomains
    X-Download-Options: noopen
    X-Content-Type-Options: nosniff
    X-Permitted-Cross-Domain-Policies: none
    Referrer-Policy: no-referrer
    X-XSS-Protection: "0"
    API-Feedback-Link: https://portal.productboard.com/zodsn5nylisgwqkcbx9rh6kp/
    Date: Tue, 17 Aug 2021 22:23:41 GMT
    Connection: keep-alive
    Keep-Alive: timeout=5
    Content-Length: "0"
  body:
    type: text
    content: ""
order: 1000
