$kind: http-request
description: This request deletes a part from a task.
url: "{{protocol}}://{{server}}:{{port}}/v2/tasks/:taskID/:partID"
method: DELETE
headers:
  Content-Type: application/x-www-form-urlencoded
pathVariables:
  taskID: "{{taskID}}"
  partID: "{{partID}}"
scripts:
  - type: afterResponse
    code: |
      pm.test("response is created", () => {
          pm.response.to.have.status(200);
      });
    language: text/javascript
examples: ./.resources/Delete part from task.resources/examples
order: 4000
