$kind: http-example
request:
  url: "{{protocol}}://{{server}}:{{port}}/v2/tasks/:taskID/invoices/:invoiceID"
  method: PATCH
  pathVariables:
    - key: taskID
      value: "15188"
      description: The taskID of the task the invoice is attached to
    - key: invoiceID
      value: "290"
      description: The invoiceID that needs to be updated
  body:
    type: json
    content: "{\r

      \    \"cost\": 10000,\r

      \    \"description\": \"new inovoice\"\r

      }"
response:
  statusCode: 200
  statusText: OK
  headers:
    Content-Security-Policy: "default-src 'self';base-uri
      'self';block-all-mixed-content;font-src 'self' https:
      data:;frame-ancestors 'self';img-src 'self' data:;object-src
      'none';script-src 'self';script-src-attr 'none';style-src 'self' https:
      'unsafe-inline';upgrade-insecure-requests"
    X-DNS-Prefetch-Control: off
    Expect-CT: max-age=0
    X-Frame-Options: SAMEORIGIN
    Strict-Transport-Security: max-age=15552000; includeSubDomains
    X-Download-Options: noopen
    X-Content-Type-Options: nosniff
    X-Permitted-Cross-Domain-Policies: none
    Referrer-Policy: no-referrer
    X-XSS-Protection: "0"
    API-Feedback-Link: https://portal.productboard.com/zodsn5nylisgwqkcbx9rh6kp/
    Date: Fri, 04 Aug 2023 19:58:47 GMT
    Connection: keep-alive
    Keep-Alive: timeout=5
    Content-Length: "0"
  body:
    type: text
    content: ""
order: 1000
