$kind: http-example
request:
  url: "{{protocol}}://{{server}}:{{port}}/v2/tasks/invoices/"
  method: GET
  queryParams:
    - key: invoices
      value: "1"
      disabled: true
      description: This parameter is used to only get specific invoices or invoices.
        This parameter accepts a comma delimited list of invoice IDs.
    - key: tasks
      value: "8250"
      disabled: true
      description: This parameter is used to only get invoices on a task or tasks.
        This parameter accepts a comma delimited list of task IDs.
    - key: start
      value: "1564895015"
      disabled: true
      description: This parameter is used to only get invoices that were logged after
        the unix timestamp passed into the start parameter. For example, all
        Invoices that were last edited after April 18th, 2018.
    - key: end
      value: "1564895015"
      disabled: true
      description: This parameter is used to only get invoices that were logged
        *before* the unix timestamp passed into the end parameter.
    - key: cursor
      value: "0"
      disabled: true
      description: This parameter is a cursor that selects what invoiceID you want to
        start receiving results at. e.g. passing 137 here will only get you
        tasks with an id greater than 137.
    - key: limit
      value: "100"
      disabled: true
      description: This parameter is a result limiter. The default is set to return no
        more than 100 results at one time.
response:
  statusCode: 200
  statusText: OK
  headers:
    X-DNS-Prefetch-Control: off
    X-Frame-Options: SAMEORIGIN
    Strict-Transport-Security: max-age=15552000; includeSubDomains
    X-Download-Options: noopen
    X-Content-Type-Options: nosniff
    X-XSS-Protection: 1; mode=block
    API-Feedback-Link: https://portal.productboard.com/zodsn5nylisgwqkcbx9rh6kp/
    Content-Type: application/json; charset=utf-8
    Content-Length: "8502"
    ETag: W/"2136-ya/k3gckYIow8xid4YYShrGMdT0"
    Date: Tue, 27 Aug 2019 18:22:25 GMT
    Connection: keep-alive
  body:
    type: json
    content: "[\r

      \    {\r

      \        \"meta\": {\r

      \            \"task\": \"/v2/tasks/?tasks=40\"\r

      \        },\r

      \        \"invoiceID\": 2,\r

      \        \"file\": \"home-depot-receipt.pdf\",\r

      \        \"cost\": 261.78,\r

      \        \"taskID\": 40,\r

      \        \"lastEdited\": 1522339851,\r

      \        \"description\": null,\r

      \        \"completedDate\": 1459391400,\r

      \        \"poItemID\": 0,\r

      \        \"invoiceFiles\": [\r

      \            {\r

      \                \"fileName\": \"home-depot-receipt.pdf\",\r

      \                \"link\":
      \"https://content.limblecmms.com/upload-36/invoices/40/home-depot-receipt\
      .pdf?Expires=1756912910&Key-Pair-Id=APKAIH5A42E3EPKJRHFQ&Signature=MeBymi\
      HtMiuORuBqmQApfPXVgvTjQIl-zpRR6fhIjsrDItx~JGtUQkDW29dEDbzFqXsckIs~EIsd6OR\
      uR8gxWcXXJopX3ZD4WjWjZKjSdz2LluwJRTp4odlTiEE2kZUoheEeIMbHJrRNQoQRPpNhJIXG\
      Zp5j5e9pqCR1R1~W3ykq-xRFmkGT7nOE0z-2ilHa9qjrgErSmrxjCRxPt0CFsYdzSySBuz4Fz\
      2mXIDQiwO1cw7SEbnqBbqKEjogjMydy7vdtUC3upG7MF2BT-bOovihxeDksLEKZdmjAwaU-nh\
      iJ4IWW1WGZ05wlHQG~xkYqDVW1R~A20qFA3-Cya0MmgQ__\"\r

      \            }\r

      \        ]\r

      \    },\r

      \    {\r

      \        \"meta\": {\r

      \            \"task\": \"/v2/tasks/?tasks=63\"\r

      \        },\r

      \        \"invoiceID\": 3,\r

      \        \"file\": null,\r

      \        \"cost\": 50,\r

      \        \"taskID\": 63,\r

      \        \"lastEdited\": 1518826313,\r

      \        \"description\": null,\r

      \        \"completedDate\": 1475597795,\r

      \        \"poItemID\": 0,\r

      \        \"invoiceFiles\": []\r

      \    }\r

      ]"
order: 1000
