$kind: http-request
url: "{{protocol}}://{{server}}:{{port}}/v2/tasks/:taskID"
method: DELETE
headers:
  Content-Type: application/json
pathVariables:
  - key: taskID
    value: "{{taskID}}"
    description: taskID of the task you are removing.
scripts:
  - type: afterResponse
    code: "pm.test(\"response should be okay to process\", function () { \r

      \    pm.response.to.not.be.error; \r

      \    pm.response.to.not.have.jsonBody(\"error\"); \r

      });"
    language: text/javascript
examples: ./.resources/Delete Task.resources/examples
order: 11000
