$kind: http-request
description: This request removes a Task Instruction from a Task.
url: "{{protocol}}://{{server}}:{{port}}/v2/tasks/instructions/:instructionID"
method: DELETE
headers:
  Content-Type: application/json
pathVariables:
  - key: instructionID
    value: "{{instructionID}}"
    description: instructionID of the instruction you are removing.
body:
  type: text
  content: ""
scripts:
  - type: afterResponse
    code: "pm.test(\"response should be okay to process\", function () { \r

      \    pm.response.to.not.be.error; \r

      \    pm.response.to.not.have.jsonBody(\"error\"); \r

      });"
    language: text/javascript
examples: ./.resources/Delete Task Instruction.resources/examples
order: 5000
