$kind: http-example
request:
  url: "{{protocol}}://{{server}}:{{port}}/v2/tasks/?tasks=97&type=2&name=%Def%&l\
    ocations=163&start=1000000000&end=2500000000&orderBy=createdDate&completedS\
    tart=0&completedEnd=2500000000&status=0&lastEditedByUsers=0,340,341"
  method: GET
  queryParams:
    - key: tasks
      value: "97"
      description: This parameter is used to only get specific Tasks. This parameter
        accepts a comma delimited list of task IDs.
    - key: assets
      value: "1"
      disabled: true
      description: This parameter is used to only get Tasks that are linked to an
        asset. This parameter accepts a comma delimited list of asset IDs.
    - key: type
      value: "2"
      description: This parameter is used to only get Tasks of a specific type. This
        parameter accepts a comma delimited list of task types.
    - key: name
      value: "%Def%"
      description: This is a parameter used to string search for a name or partial
        name of a task this parameter expects a string with the wildcard %.
    - key: locations
      value: "163"
      description: This parameter is used to only get Tasks at a specific group of
        Locations. This parameter accepts a comma delimited list of Location
        IDs.
    - key: start
      value: "1000000000"
      description: This parameter is used to only get Tasks that were last edited
        after the unix timestamp passed into the start parameter. For example,
        all Tasks that were last edited after April 18th, 2018.
    - key: end
      value: "2500000000"
      description: This parameter is used to only get Tasks that were last edited
        *before* the unix timestamp passed into the end parameter.
    - key: cursor
      value: "0"
      disabled: true
      description: This parameter is a cursor that selects what taskID you want to
        start receiving results at. e.g. passing 137 here will only get you
        tasks with an id greater than 137.
    - key: limit
      value: "2"
      disabled: true
      description: This parameter is a result limiter. The default is set to return no
        more than 100 results at one time.
    - key: orderBy
      value: createdDate
      description: This parameter sorts based on the value you pass. I.e. passing
        createdDate will order the results based on createdDate. Negative
        parameters are used to reverse sort order. This supports sorting by due,
        createdDate, and dateCompleted.
    - key: completedStart
      value: "0"
      description: This parameter is used to only get Tasks that were completed after
        the unix timestamp passed into this parameter. For example, all Assets
        that were completed after April 18th, 2018.
    - key: completedEnd
      value: "2500000000"
      description: This parameter is used to only get Tasks that were completed
        *before* the unix timestamp passed into this parameter.
    - key: status
      value: "0"
      description: This parameter is used to filter tasks by completed status. 1 -
        Complete  0 - Incomplete
    - key: lastEditedByUsers
      value: 0,340,341
      description: This parameter is used to filter tasks by users that have completed
        tasks.
    - key: meta1
      value: "1"
      disabled: true
      description: This parameter is used to filter tasks by task meta data. This does
        not show in the web application, but can be used to track items between
        integrated systems.
    - key: meta2
      value: "2"
      disabled: true
      description: This parameter is used to filter tasks by task meta data. This does
        not show in the web application, but can be used to track items between
        integrated systems.
    - key: meta3
      value: "3"
      disabled: true
      description: This parameter is used to filter tasks by task meta data. This does
        not show in the web application, but can be used to track items between
        integrated systems.
    - key: statusIDs
      value: 0,1,2
      disabled: true
      description: This parameter is used to filter tasks by their associated statusID.
    - key: page
      value: "2"
      disabled: true
      description: This parameter is used to paginate results based on the limit.
        Refer to Pagination section for more information.
    - key: geoLocation
      value: "true"
      disabled: true
      description: This parameter is used to filter results that contain a geoLocation
        property. By default it is false and will return **all** tasks with and
        without geoLocation property. If true, it will only return tasks with a
        geoLocation property.
response:
  statusCode: 200
  statusText: OK
  headers:
    Content-Security-Policy: "default-src 'self';base-uri
      'self';block-all-mixed-content;font-src 'self' https:
      data:;frame-ancestors 'self';img-src 'self' data:;object-src
      'none';script-src 'self';script-src-attr 'none';style-src 'self' https:
      'unsafe-inline';upgrade-insecure-requests"
    X-DNS-Prefetch-Control: off
    Expect-CT: max-age=0
    X-Frame-Options: SAMEORIGIN
    Strict-Transport-Security: max-age=15552000; includeSubDomains
    X-Download-Options: noopen
    X-Content-Type-Options: nosniff
    X-Permitted-Cross-Domain-Policies: none
    Referrer-Policy: no-referrer
    X-XSS-Protection: "0"
    API-Feedback-Link: https://portal.productboard.com/zodsn5nylisgwqkcbx9rh6kp/
    Content-Type: application/json; charset=utf-8
    Content-Length: "925"
    ETag: W/"39d-33jSb8B3/Y570UWJ/3/Pv2Jz0cs"
    Date: Thu, 15 Sep 2022 21:01:39 GMT
    Connection: keep-alive
    Keep-Alive: timeout=5
  body:
    type: json
    content: |-
      [
          {
              "meta": {
                  "invoices": "/v2/tasks/invoices/?tasks=97",
                  "labor": "/v2/tasks/labor/?tasks=97",
                  "partsUsage": "/v2/parts/usage/?tasks=97",
                  "instructions": "/v2/tasks/97/instructions",
                  "status": "/v2/statuses/?statuses=0"
              },
              "taskID": 97,
              "name": "Default WO Template - '\"r'\"",
              "userID": 0,
              "teamID": 0,
              "locationID": 163,
              "template": true,
              "createdDate": 1490260854,
              "startDate": 0,
              "scheduledStart": 0,
              "scheduledEnd": 0,
              "due": 0,
              "description": "",
              "dateCompleted": 0,
              "lastEdited": 1518826313,
              "lastEditedByUser": 0,
              "completedByUser": 0,
              "assetID": 0,
              "completedUserWage": 15,
              "priority": 0,
              "priorityID": null,
              "downtime": 0,
              "completionNotes": null,
              "requestorName": null,
              "requestorEmail": null,
              "requestorPhone": null,
              "requestTitle": null,
              "requestField1": null,
              "requestField2": null,
              "requestField3": null,
              "requestDropdown1": null,
              "requestDropdown2": null,
              "requestDropdown3": null,
              "requestorDescription": null,
              "meta1": null,
              "meta2": null,
              "meta3": null,
              "statusID": 0,
              "geoLocation": null,
              "type": 2,
              "associatedTaskID": 0,
              "status": 0
          }
      ]
order: 2000
