$kind: http-request
url: "{{protocol}}://{{server}}:{{port}}/v2/tasks/instructions/:instructionID/o\
  ptions/:instructionOptionID"
method: PATCH
pathVariables:
  - key: instructionID
    value: "49343"
    description: instructionID of the instruction whose option you are editing.
  - key: instructionOptionID
    value: "7097"
    description: instructionOptionID of the option you are editing.
body:
  type: json
  content: "{\r

    \    \"instruction\": \"Not Allowed\",\r

    \    \"instructionOptionOrder\":1\r

    \    \r

    }"
examples: ./.resources/Update Instruction Option.resources/examples
order: 4000
