$kind: http-request
description: This request will attach a text or image file to an invoice on an
  **open** Task (i.e. task status=0).
url: "{{protocol}}://{{server}}:{{port}}/v2/tasks/:taskID/invoices/:invoiceID/file"
method: PUT
pathVariables:
  - key: taskID
    value: "15188"
    description: The taskID of the invoice you want add the file to.
  - key: invoiceID
    value: "311"
    description: The invoiceID of the invoice you want to attach the file to.
body:
  type: formdata
  content:
    - type: file
      key: file
      src: /C:/Users/Hely Mehta/Desktop/basic.txt
examples: ./.resources/Attach a file to an invoice.resources/examples
order: 1000
