$kind: http-request
description: |-
  This request gets the labor (time spent) on a Task. A single Task can have multiple times logged onto it.

  <p><b>Return data description</b></p>

  <table><tbody><tr><th>Property</th><th>Description</th></tr><tr><td><div>meta</div><div contenteditable="false"><div><div><div></div></div></div><div></div></div></td><td><div>This property contains shortcuts to other requests that can be used to get more information regarding the Task the labor was logged on and the user who logged the time.</div><div contenteditable="false"><div><div><div></div></div></div><div></div></div></td></tr><tr><td><div>taskID</div><div contenteditable="false"><div><div><div></div></div></div><div></div></div></td><td><div>The Task ID associated with this labor entry.</div><div contenteditable="false"><div><div><div></div></div></div><div></div></div></td></tr><tr><td><div>timeSpent</div><div contenteditable="false"><div><div><div></div></div></div><div></div></div></td><td><div>The amount of time measure in seconds.</div><div contenteditable="false"><div><div><div></div></div></div><div></div></div></td></tr><tr><td><div>userWage</div><div contenteditable="false"><div><div><div></div></div></div><div></div></div></td><td><div>The wage per hour.</div><div contenteditable="false"><div><div><div></div></div></div><div></div></div></td></tr><tr><td><div>description</div><div contenteditable="false"><div><div><div></div></div></div><div></div></div></td><td><div>A description of the labor entry.</div><div contenteditable="false"><div><div><div></div></div></div><div></div></div></td></tr><tr><td><div>dateLogged</div><div contenteditable="false"><div><div><div></div></div></div><div></div></div></td><td><div>The date that this time was logged on the Task.</div><div contenteditable="false"><div><div><div></div></div></div><div></div></div></td></tr><tr><td><div>billableTime</div><div contenteditable="false"><div><div><div></div></div></div><div></div></div></td><td><div>The amount of time that is billable for this Task.</div><div contenteditable="false"><div><div><div></div></div></div><div></div></div></td></tr><tr><td><div>billableRate</div><div contenteditable="false"><div><div><div></div></div></div><div></div></div></td><td><div>The rate at which this labor entry is billed at.</div><div contenteditable="false"><div><div><div></div></div></div><div></div></div></td></tr><tr><td><div>categoryID</div><div contenteditable="false"><div><div><div></div></div></div><div></div></div></td><td><div>The labor category this entry is associated with.</div><div contenteditable="false"><div><div><div></div></div></div><div></div></div></td></tr><tr><td><div>taskName</div><div contenteditable="false"><div><div><div></div></div></div><div></div></div></td><td><div>The name of the task associated with this labor entry.</div><div contenteditable="false"><div><div><div></div></div></div><div></div></div></td></tr><tr><td><div>taskPriorityID</div><div contenteditable="false"><div><div><div></div></div></div><div></div></div></td><td><div>The Priority ID of the task this labor entry is associated with.</div><div contenteditable="false"><div><div><div></div></div></div><div></div></div></td></tr><tr><td><div>taskPriorityLevel</div><div contenteditable="false"><div><div><div></div></div></div><div></div></div></td><td><div>The Priority value of the task this labor entry is associated with.</div><div contenteditable="false"><div><div><div></div></div></div><div></div></div></td></tr></tbody></table>
url: "{{protocol}}://{{server}}:{{port}}/v2/tasks/labor?tasks=6,11&users=0&star\
  t=1564895015&end=1564895015&limit=100&cursor=0&locations=0&orderBy=-dateLogge\
  d"
method: GET
queryParams:
  - key: tasks
    value: 6,11
    description: This parameter is used to only get specific Tasks. This parameter
      accepts a comma delimited list of task IDs.
  - key: users
    value: "0"
    description: This parameter is used to only get labor records for a specific
      user or set of users in a comma delimited list.
  - key: start
    value: "1564895015"
    description: This parameter is used to only get labor that was logged after the
      unix timestamp passed into the start parameter. For example, all Assets
      that were last edited after April 18th, 2018.
  - key: end
    value: "1564895015"
    description: This parameter is used to only get labor that was logged *before*
      the unix timestamp passed into the end parameter.
  - key: limit
    value: "100"
    description: This parameter is a result limiter. The default is set to return no
      more than 100 results at one time.
  - key: cursor
    value: "0"
    description: This parameter is a cursor that selects what taskID you want to
      start receiving results at. e.g. passing 137 here will only get you tasks
      with an id greater than 137.
  - key: locations
    value: "0"
    description: This parameter is used to retrieve labor entries for particular
      locations. This parameter accepts a comma delimited list of location IDs.
  - key: orderBy
    value: -dateLogged
    description: This parameter is used to order results by their dateLogged
      property instead of the default ordering. CANNOT be provided alongside the
      cursor parameter. to paginate in this ordering, use the start or end
      parameters.
scripts:
  - type: afterResponse
    code: "pm.test(\"response must be valid and have a body\", function () {\r

      \     // assert that the status code is 200\r

      \     pm.response.to.be.ok; // info, success, redirection,
      clientError,  serverError, are other variants\r

      \     // assert that the response has a valid JSON body\r

      \     pm.response.to.be.withBody;\r

      \     pm.response.to.be.json; // this assertion also checks if a
      body  exists, so the above check is not needed\r

      });"
    language: text/javascript
examples: ./.resources/Task Labor.resources/examples
order: 1000
