$kind: http-example
request:
  url: "{{protocol}}://{{server}}:{{port}}/v2/tasks/:taskID/parts"
  method: PUT
  headers:
    Content-Type: application/json
  pathVariables:
    taskID: "8290"
  body:
    type: text
    content: |-
      {
      	"partID": {{partID}},
      	"quantity": 10
      }
response:
  statusCode: 200
  statusText: OK
  headers:
    X-DNS-Prefetch-Control: off
    X-Frame-Options: SAMEORIGIN
    Strict-Transport-Security: max-age=15552000; includeSubDomains
    X-Download-Options: noopen
    X-Content-Type-Options: nosniff
    X-XSS-Protection: 1; mode=block
    API-Feedback-Link: https://portal.productboard.com/zodsn5nylisgwqkcbx9rh6kp/
    Date: Thu, 12 Sep 2019 17:51:02 GMT
    Connection: keep-alive
    Content-Length: "0"
  body:
    type: text
    content: ""
order: 1000
