$kind: http-example
request:
  url: "{{protocol}}://{{server}}:{{port}}/v2/tasks/:taskID/instructions/"
  method: POST
  headers:
    Content-Type: application/json
  pathVariables:
    - key: taskID
      value: "8250"
      description: taskID of the task you are adding instructions to.
  body:
    type: text
    content: |-
      {
      	"type": 1,
      	"instruction": "hahaha",
      	"parentInstructionID": 34065
      }
response:
  statusCode: 201
  statusText: Created
  headers:
    X-DNS-Prefetch-Control: off
    X-Frame-Options: SAMEORIGIN
    Strict-Transport-Security: max-age=15552000; includeSubDomains
    X-Download-Options: noopen
    X-Content-Type-Options: nosniff
    X-XSS-Protection: 1; mode=block
    API-Feedback-Link: https://portal.productboard.com/zodsn5nylisgwqkcbx9rh6kp/
    Location: /v2/tasks/8250/instructions
    Content-Type: application/json; charset=utf-8
    Content-Length: "23"
    ETag: W/"17-K7sZAuyBoV91EhuvXAM934e1EM8"
    Date: Tue, 27 Aug 2019 18:18:33 GMT
    Connection: keep-alive
  body:
    type: json
    content: |-
      {
          "instructionID": 34068
      }
order: 1000
