$kind: http-example
request:
  url: "{{protocol}}://{{server}}:{{port}}/v2/tasks/:taskID/instructions/:instruc\
    tionID/options"
  method: GET
  pathVariables:
    - key: taskID
      value: "11429"
      description: taskID of the task you are getting the option/dropdown list.
    - key: instructionID
      value: "49343"
      description: instructionID of the option/dropdown list you are getting the
        options for.
response:
  statusCode: 200
  statusText: OK
  headers:
    Content-Security-Policy: "default-src 'self';base-uri
      'self';block-all-mixed-content;font-src 'self' https:
      data:;frame-ancestors 'self';img-src 'self' data:;object-src
      'none';script-src 'self';script-src-attr 'none';style-src 'self' https:
      'unsafe-inline';upgrade-insecure-requests"
    X-DNS-Prefetch-Control: off
    Expect-CT: max-age=0
    X-Frame-Options: SAMEORIGIN
    Strict-Transport-Security: max-age=15552000; includeSubDomains
    X-Download-Options: noopen
    X-Content-Type-Options: nosniff
    X-Permitted-Cross-Domain-Policies: none
    Referrer-Policy: no-referrer
    X-XSS-Protection: "0"
    API-Feedback-Link: https://portal.productboard.com/zodsn5nylisgwqkcbx9rh6kp/
    Content-Type: application/json; charset=utf-8
    Content-Length: "152"
    ETag: W/"98-spEkVz4oblUkvPKD14UDRII/gVs"
    Date: Tue, 17 Aug 2021 22:20:48 GMT
    Connection: keep-alive
    Keep-Alive: timeout=5
  body:
    type: json
    content: |-
      [
          {
              "instructionOptionID": 7096,
              "instructionOptionOrder": 1,
              "instruction": "Yes"
          },
          {
              "instructionOptionID": 7097,
              "instructionOptionOrder": 2,
              "instruction": "No"
          }
      ]
order: 1000
