$kind: http-example
request:
  url: "{{protocol}}://{{server}}:{{port}}/v2/tasks/:taskID/parts"
  method: GET
  headers:
    Content-Type: application/json
  pathVariables:
    taskID: "8466"
response:
  statusCode: 200
  statusText: OK
  headers:
    X-DNS-Prefetch-Control: off
    X-Frame-Options: SAMEORIGIN
    Strict-Transport-Security: max-age=15552000; includeSubDomains
    X-Download-Options: noopen
    X-Content-Type-Options: nosniff
    X-XSS-Protection: 1; mode=block
    API-Feedback-Link: https://portal.productboard.com/zodsn5nylisgwqkcbx9rh6kp/
    Content-Type: application/json; charset=utf-8
    Content-Length: "172"
    ETag: W/"ac-Ej0l5qDTe+vCTifFJGxBVewcFDc"
    Date: Thu, 13 Feb 2020 21:42:52 GMT
    Connection: keep-alive
  body:
    type: json
    content: |-
      [
          {
              "partID": 2934,
              "quantity": 1,
              "usedPrice": 1,
              "partName": "Lawn Mower Blade",
              "poItemID": 0
          },
          {
              "partID": 2992,
              "quantity": 1,
              "usedPrice": 4.99,
              "partName": "Cog",
              "poItemID": 0
          }
      ]
order: 1000
