$kind: http-request
description: This request removes a file attached to an invoice on an open Task
  (i.e. task status = 0).
url: "{{protocol}}://{{server}}:{{port}}/v2/tasks/:taskID/invoices/:invoiceID/file"
method: DELETE
pathVariables:
  - key: taskID
    value: "15188"
    description: The taskID of the invoice you want remove the file from.
  - key: invoiceID
    value: "311"
    description: The invoiceID of the invoice you want to remove the file from.
examples: ./.resources/Delete file from Invoice.resources/examples
order: 2000
