$kind: http-example
request:
  url: "{{protocol}}://{{server}}:{{port}}/v2/roles/"
  method: GET
  queryParams:
    - key: roles
      value: "1032"
      disabled: true
    - key: name
      value: "%view%"
      disabled: true
    - key: cursor
      value: "0"
      disabled: true
    - key: limit
      value: "100"
      disabled: true
response:
  statusCode: 200
  statusText: OK
  headers:
    X-DNS-Prefetch-Control: off
    X-Frame-Options: SAMEORIGIN
    Strict-Transport-Security: max-age=15552000; includeSubDomains
    X-Download-Options: noopen
    X-Content-Type-Options: nosniff
    X-XSS-Protection: 1; mode=block
    API-Feedback-Link: https://portal.productboard.com/zodsn5nylisgwqkcbx9rh6kp/
    Content-Type: application/json; charset=utf-8
    Content-Length: "122"
    ETag: W/"7a-+4u7wr4+PG1D3neyUxIACbrENn8"
    Date: Tue, 27 Aug 2019 16:37:27 GMT
    Connection: keep-alive
  body:
    type: json
    content: |-
      [
          {
              "roleID": 321,
              "name": "Manager"
          }
      ]
order: 1000
