$kind: http-request
description: >
  Gets parts attached to a task.


  This request gets parts associated with a task.  A single Task can have
  multiple parts associated with it.


  <p><b>Return data description</b></p>

  <table>
      <thead>
          <tr>
              <th>Property</th>
              <th>Description</th>
          </tr>
      </thead>
      <tbody>
          <tr>
              <td>partID</td>
              <td>The partID of the part associated to this task.</td>
          </tr>
          <tr>
              <td>quantity</td>
              <td>The quantity of this part associated to this task.</td>
          </tr>
          <tr>
              <td>usedPrice</td>
              <td>The price of the part at the time of use.</td>
          </tr>
          <tr>
              <td>partName</td>
              <td>The name of the part.</td>
          </tr>
          <tr>
              <td>poItemID</td>
              <td>The unique ID of the PO item associated with this record.</td>
          </tr>
      </tbody>
  </table>
url: "{{protocol}}://{{server}}:{{port}}/v2/tasks/:taskID/parts"
method: GET
headers:
  Content-Type: application/json
pathVariables:
  taskID: "{{taskID}}"
scripts:
  - type: afterResponse
    code: |
      pm.test("response exists", () => {
          pm.response.to.have.status(200);
      });
    language: text/javascript
examples: ./.resources/Get attached parts.resources/examples
order: 1000
