$kind: http-example
request:
  url: "{{protocol}}://{{server}}:{{port}}/v2/tasks/:taskID/instructions/:instruc\
    tionID/options"
  method: POST
  pathVariables:
    - key: taskID
      value: "11429"
      description: taskID of the task you are getting the option/dropdown list.
    - key: instructionID
      value: "49343"
      description: instructionID of the option/dropdown list you are getting the
        options for.
  body:
    type: json
    content: "{\r

      \t\"instruction\": \"Yes\",\r

      \    \"instructionOptionOrder\": 1\r

      }"
response:
  statusCode: 201
  statusText: Created
  headers:
    Content-Security-Policy: "default-src 'self';base-uri
      'self';block-all-mixed-content;font-src 'self' https:
      data:;frame-ancestors 'self';img-src 'self' data:;object-src
      'none';script-src 'self';script-src-attr 'none';style-src 'self' https:
      'unsafe-inline';upgrade-insecure-requests"
    X-DNS-Prefetch-Control: off
    Expect-CT: max-age=0
    X-Frame-Options: SAMEORIGIN
    Strict-Transport-Security: max-age=15552000; includeSubDomains
    X-Download-Options: noopen
    X-Content-Type-Options: nosniff
    X-Permitted-Cross-Domain-Policies: none
    Referrer-Policy: no-referrer
    X-XSS-Protection: "0"
    API-Feedback-Link: https://portal.productboard.com/zodsn5nylisgwqkcbx9rh6kp/
    Content-Type: application/json; charset=utf-8
    Content-Length: "28"
    ETag: W/"1c-mTmLC9bbeiZlEXaN1Zy3AiwFBpc"
    Date: Tue, 17 Aug 2021 22:19:01 GMT
    Connection: keep-alive
    Keep-Alive: timeout=5
  body:
    type: json
    content: |-
      {
          "instructionOptionID": 7097
      }
order: 1000
