$kind: http-example
request:
  url: "{{protocol}}://{{server}}:{{port}}/v2/tasks/:taskID/tags"
  method: PUT
  headers:
    Content-Type: application/json
  pathVariables:
    taskID: "1160"
  body:
    type: text
    content: |-
      {
        "tags": ["@Food", "@Safety"]
      }
response:
  statusCode: 400
  statusText: Bad Request
  headers:
    Content-Type: application/json
  body:
    type: text
    content: |-
      {
        "added": [],
        "name": "@Bad;Name",
        "message": "The ';' character is not allowed in custom tags.",
        "sanitizations": []
      }
order: 3000
